In [111]:
import pandas as pd
from pathlib import Path
import ast
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

## Ingestao dos dados

In [46]:
data_source = Path(r"C:\Users\dougl\OneDrive\Área de Trabalho\POS\pratica do que aprendi\modulo01-fundamentos-de-ia-e-llms-para-programadores\exemplo-01\Redes Neurais\data\Bank_churn.csv")

In [47]:
df = pd.read_csv(data_source)

## Exploracao dos dados

In [ ]:
# df.head()

,id,CustomerId,Surname,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Rating,Exited,"Geography:str,Gender:str"
0,0.0,15674932.0,"O,k{wudilic_-huk>wu_",668.0,33.0,3.0,0.00,2.0,1.0,0.0,181449.97,-3,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
1,1.0,15749177.0,"O{kwudi""li#%%'oli=-sa",627.0,33.0,1.0,0.00,2.0,1.0,1.0,49503.5,0,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
2,2.0,15694510.0,Hsueh,678.0,40.0,10.0,0.00,2.0,1.0,0.0,184866.69,1,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
3,3.0,15741417.0,"Kao,]?>?%]@",581.0,34.0,2.0,148882.54,1.0,1.0,1.0,84560.88,-4,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
4,4.0,15766172.0,Ch-i]emen'-am,716.0,33.0,5.0,0.00,2.0,1.0,1.0,15068.83,-1,0,"{'Geography': 'Madrid-Spain','Gender': 'Male'}"

In [ ]:
# df.columns

Index(['id', 'CustomerId', 'Surname', 'CreditScore', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Rating', 'Exited', 'Geography:str,Gender:str'],
      dtype='str')

In [ ]:
# df["Geography:str,Gender:str"].head(10)

0      {'Geography': 'Paris-France','Gender': 'Male'}
1      {'Geography': 'Paris-France','Gender': 'Male'}
2      {'Geography': 'Paris-France','Gender': 'Male'}
3      {'Geography': 'Paris-France','Gender': 'Male'}
4      {'Geography': 'Madrid-Spain','Gender': 'Male'}
5     {'Geography': 'Berlin-Gernay','Gender': 'Male'}
6    {'Geography': 'Paris-France','Gender': 'Female'}
7      {'Geography': 'Madrid-Spain','Gender': 'Male'}
8      {'Geography': 'Paris-France','Gender': 'Male'}
9     {'Geography': 'Berlin-Gernay','Gender': 'Male'}
Name: Geography:str,Gender:str, dtype: str

In [ ]:
# df["Exited"].value_counts()

Exited
0    130113
1     34921
Name: count, dtype: int64

In [ ]:
# df["Rating"].value_counts()

Rating
-4    16779
 2    16683
 0    16577
-3    16528
-2    16449
 1    16435
 3    16420
 4    16405
-5    16380
-1    16378
Name: count, dtype: int64

In [ ]:
# df.isnull().sum()

id                          7186
CustomerId                  7526
Surname                     3917
CreditScore                  370
Age                         5599
Tenure                      4707
Balance                     4041
NumOfProducts               5521
HasCrCard                   2843
IsActiveMember              3525
EstimatedSalary             4377
Rating                         0
Exited                         0
Geography:str,Gender:str       0
dtype: int64

In [ ]:
# df["Geography:str,Gender:str"].value_counts()

Geography:str,Gender:str
{'Geography': 'Paris-France','Gender': 'Male'}       51226
{'Geography': 'Paris-France','Gender': 'Female'}     37819
{'Geography': 'Madrid-Spain','Gender': 'Male'}       19605
{'Geography': 'Berlin-Gernay','Gender': 'Male'}      17265
{'Geography': 'Berlin-Gernay','Gender': 'Female'}    15505
{'Geography': 'Madrid-Spain','Gender': 'Female'}     14684
{'Geography': 'Paris-France','Gender': 'nan'}         4733
{'Geography': 'Madrid-Spain','Gender': 'nan'}         1761
{'Geography': 'Berlin-Gernay','Gender': 'nan'}        1691
{'Geography': 'nan','Gender': 'Male'}                  401
{'Geography': 'nan','Gender': 'Female'}                314
{'Geography': 'nan','Gender': 'nan'}                    30
Name: count, dtype: int64

In [ ]:
# df["Age"].describe()

count     159435
unique       500
top         38.0
freq        8897
Name: Age, dtype: object

In [ ]:
# df["EstimatedSalary"].describe()

count       160657
unique       54398
top       88890.05
freq           174
Name: EstimatedSalary, dtype: object

In [ ]:
# df["Age"].head(20).tolist()

['33.0',
 '33.0',
 '40.0',
 '34.0',
 '33.0',
 '36.0',
 '30.0',
 '37.0',
 '43.0',
 '40.0',
 '27.0',
 nan,
 '71.0',
 '47.0',
 '33.0',
 '25.0',
 '36.0',
 '36.0',
 '55.0',
 '61.0']

In [ ]:
# df["EstimatedSalary"].head(20).tolist()

['181449.97',
 '49503.5',
 '184866.69',
 '84560.88',
 '15068.83',
 '136024.31',
 '29792.11',
 '106851.6',
 '142917.13',
 '170843.07',
 '109184.24',
 nan,
 '93081.87',
 '72945.68',
 '79997.14',
 '162260.93',
 '135082.47',
 '111573.3',
 '125083.29',
 '180890.4']

In [ ]:
# df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
# df["EstimatedSalary"] = pd.to_numeric(df["EstimatedSalary"], errors="coerce")

In [ ]:
# df[["Age", "EstimatedSalary"]].dtypes

Age                float64
EstimatedSalary    float64
dtype: object

In [ ]:
# df.isnull().sum()

id                          7186
CustomerId                  7526
Surname                     3917
CreditScore                  370
Age                         6108
Tenure                      4707
Balance                     4041
NumOfProducts               5521
HasCrCard                   2843
IsActiveMember              3525
EstimatedSalary             4577
Rating                         0
Exited                         0
Geography:str,Gender:str       0
dtype: int64

## Aqui comecamos a criar os dataframes de tranformacao

In [48]:
df_model = df[
    [
        "CreditScore",
        "Age",
        "Tenure",
        "Balance",
        "NumOfProducts",
        "HasCrCard",
        "IsActiveMember",
        "EstimatedSalary",
        "Geography:str,Gender:str",
        "Exited"
    ]
].copy()

In [49]:
df_model.info()

<class 'pandas.DataFrame'>
RangeIndex: 165034 entries, 0 to 165033
Data columns (total 10 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CreditScore               164664 non-null  float64
 1   Age                       159435 non-null  str
 2   Tenure                    160327 non-null  float64
 3   Balance                   160993 non-null  float64
 4   NumOfProducts             159513 non-null  float64
 5   HasCrCard                 162191 non-null  float64
 6   IsActiveMember            161509 non-null  float64
 7   EstimatedSalary           160657 non-null  str
 8   Geography:str,Gender:str  165034 non-null  str
 9   Exited                    165034 non-null  int64
dtypes: float64(6), int64(1), str(3)
memory usage: 12.6 MB

In [50]:
ast.literal_eval(df_model["Geography:str,Gender:str"].iloc[0])

{'Geography': 'Paris-France', 'Gender': 'Male'}

In [51]:
df_model["Geography"]= df_model["Geography:str,Gender:str"].apply(
    lambda x: ast.literal_eval(x)["Geography"]
)

df_model["Gender"]= df_model["Geography:str,Gender:str"].apply(
    lambda x: ast.literal_eval(x)["Gender"]
)

In [52]:
df_model[["Geography", "Gender"]].head(10)

       Geography  Gender
0   Paris-France    Male
1   Paris-France    Male
2   Paris-France    Male
3   Paris-France    Male
4   Madrid-Spain    Male
5  Berlin-Gernay    Male
6   Paris-France  Female
7   Madrid-Spain    Male
8   Paris-France    Male
9  Berlin-Gernay    Male

In [54]:
df_model["Geography"].value_counts(dropna=False)

Geography
Paris-France     93778
Madrid-Spain     36050
Berlin-Gernay    34461
nan                745
Name: count, dtype: int64

In [55]:
df_model["Gender"].value_counts(dropna=False)

Gender
Male      88497
Female    68322
nan        8215
Name: count, dtype: int64

In [56]:
df_model["Gender"].isna().sum()

np.int64(0)

In [57]:
df_model["Gender"].dtype

In [58]:
df_model["Gender"] = df_model["Gender"].replace("nan", pd.NA)
df_model["Geography"] = df_model["Geography"].replace("nan", pd.NA)

In [59]:
df_model[["Gender", "Geography"]].isna().sum()

Gender       8215
Geography     745
dtype: int64

In [60]:
df_model["Geography"] = df_model["Geography"].replace(
    "Berlin-Gernay", "Berlin-Germany"
)

In [61]:
df_model["Geography"].value_counts(dropna = False)

Geography
Paris-France      93778
Madrid-Spain      36050
Berlin-Germany    34461
NaN                 745
Name: count, dtype: int64

In [62]:
df_model["Gender"] = df_model["Gender"].fillna("Unknown")
df_model["Geography"] = df_model["Geography"].fillna("Unknown")

In [63]:
df_model[["Geography", "Gender"]].value_counts()

Geography       Gender
Paris-France    Male       51226
                Female     37819
Madrid-Spain    Male       19605
Berlin-Germany  Male       17265
                Female     15505
Madrid-Spain    Female     14684
Paris-France    Unknown     4733
Madrid-Spain    Unknown     1761
Berlin-Germany  Unknown     1691
Unknown         Male         401
                Female       314
                Unknown       30
Name: count, dtype: int64

In [64]:
df_model = pd.get_dummies(
    df_model,
    columns = ["Geography", "Gender"]
)

In [65]:
df_model.head()

   CreditScore   Age  Tenure  ...  Gender_Female  Gender_Male  Gender_Unknown
0        668.0  33.0     3.0  ...          False         True           False
1        627.0  33.0     1.0  ...          False         True           False
2        678.0  40.0    10.0  ...          False         True           False
3        581.0  34.0     2.0  ...          False         True           False
4        716.0  33.0     5.0  ...          False         True           False

[5 rows x 17 columns]

In [66]:
df_model.dtypes

CreditScore                 float64
Age                             str
Tenure                      float64
Balance                     float64
NumOfProducts               float64
HasCrCard                   float64
IsActiveMember              float64
EstimatedSalary                 str
Geography:str,Gender:str        str
Exited                        int64
Geography_Berlin-Germany       bool
Geography_Madrid-Spain         bool
Geography_Paris-France         bool
Geography_Unknown              bool
Gender_Female                  bool
Gender_Male                    bool
Gender_Unknown                 bool
dtype: object

In [67]:
df_model = df_model.drop(columns=["Geography:str,Gender:str"])

In [90]:
df_model["Age"] = pd.to_numeric(
    df_model["Age"],
    errors = "coerce"
)

df_model["EstimatedSalary"] = pd.to_numeric(
    df_model["EstimatedSalary"],
    errors = "coerce"
)

In [91]:
df_model.info()

<class 'pandas.DataFrame'>
RangeIndex: 165034 entries, 0 to 165033
Data columns (total 16 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CreditScore               164664 non-null  float64
 1   Age                       158926 non-null  float64
 2   Tenure                    160327 non-null  float64
 3   Balance                   160993 non-null  float64
 4   NumOfProducts             159513 non-null  float64
 5   HasCrCard                 162191 non-null  float64
 6   IsActiveMember            161509 non-null  float64
 7   EstimatedSalary           160457 non-null  float64
 8   Exited                    165034 non-null  int64
 9   Geography_Berlin-Germany  165034 non-null  bool
 10  Geography_Madrid-Spain    165034 non-null  bool
 11  Geography_Paris-France    165034 non-null  bool
 12  Geography_Unknown         165034 non-null  bool
 13  Gender_Female             165034 non-null  bool
 14  Gender_Male               165034 non-null  bool
 15  Gender_Unknown            165034 non-null  bool
dtypes: bool(7), float64(8), int64(1)
memory usage: 12.4 MB

In [92]:
df_model.head()

   CreditScore   Age  Tenure  ...  Gender_Female  Gender_Male  Gender_Unknown
0        668.0  33.0     3.0  ...          False         True           False
1        627.0  33.0     1.0  ...          False         True           False
2        678.0  40.0    10.0  ...          False         True           False
3        581.0  34.0     2.0  ...          False         True           False
4        716.0  33.0     5.0  ...          False         True           False

[5 rows x 16 columns]

In [93]:
x = df_model.drop(columns="Exited")
y = df_model["Exited"]

In [94]:
x.head()

   CreditScore   Age  Tenure  ...  Gender_Female  Gender_Male  Gender_Unknown
0        668.0  33.0     3.0  ...          False         True           False
1        627.0  33.0     1.0  ...          False         True           False
2        678.0  40.0    10.0  ...          False         True           False
3        581.0  34.0     2.0  ...          False         True           False
4        716.0  33.0     5.0  ...          False         True           False

[5 rows x 15 columns]

In [95]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Exited, dtype: int64

In [96]:
x.info()

<class 'pandas.DataFrame'>
RangeIndex: 165034 entries, 0 to 165033
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CreditScore               164664 non-null  float64
 1   Age                       158926 non-null  float64
 2   Tenure                    160327 non-null  float64
 3   Balance                   160993 non-null  float64
 4   NumOfProducts             159513 non-null  float64
 5   HasCrCard                 162191 non-null  float64
 6   IsActiveMember            161509 non-null  float64
 7   EstimatedSalary           160457 non-null  float64
 8   Geography_Berlin-Germany  165034 non-null  bool
 9   Geography_Madrid-Spain    165034 non-null  bool
 10  Geography_Paris-France    165034 non-null  bool
 11  Geography_Unknown         165034 non-null  bool
 12  Gender_Female             165034 non-null  bool
 13  Gender_Male               165034 non-null  bool
 14  Gender_Unknown            165034 non-null  bool
dtypes: bool(7), float64(8)
memory usage: 11.2 MB

In [97]:
x.shape

(165034, 15)

In [98]:
y.shape

(165034,)

In [99]:
x.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Geography_Berlin-Germany',
       'Geography_Madrid-Spain', 'Geography_Paris-France', 'Geography_Unknown',
       'Gender_Female', 'Gender_Male', 'Gender_Unknown'],
      dtype='str')

In [100]:
X_train, X_test, Y_train, Y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42
)

In [101]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("Y_train:", Y_train.shape)
print("Y_test :", Y_test.shape)

X_train: (132027, 15)
X_test : (33007, 15)
Y_train: (132027,)
Y_test : (33007,)

In [102]:
imputer = SimpleImputer(strategy="median")

In [103]:
X_train.isna().sum()

CreditScore                  293
Age                         4867
Tenure                      3771
Balance                     3219
NumOfProducts               4403
HasCrCard                   2331
IsActiveMember              2790
EstimatedSalary             3699
Geography_Berlin-Germany       0
Geography_Madrid-Spain         0
Geography_Paris-France         0
Geography_Unknown              0
Gender_Female                  0
Gender_Male                    0
Gender_Unknown                 0
dtype: int64

In [104]:
numeric_columns =[
    "CreditScore",
    "Age",
    "Tenure",
    "Balance",
    "NumOfProducts",
    "HasCrCard",
    "IsActiveMember",
    "EstimatedSalary"
]

In [106]:
imputer.fit(X_train[numeric_columns])

SimpleImputer(strategy='median')

In [107]:
X_train[numeric_columns] = imputer.transform(
    X_train[numeric_columns]
)

In [109]:
X_test[numeric_columns] = imputer.transform(
    X_test[numeric_columns]
)

In [112]:
scaler = StandardScaler()